version: '3'
services:
  flask:
      build: ./flask
      container_name: flask
      image: "flask:test"
      ports:
       - "5000:5000"
      networks:
      - backend
  nginx:
      build: ./nginx
      container_name: nginx
      image: "nginx:test"
      ports:
       - "80:80"
      networks:
       - backend

networks:
  backend:
    driver: bridge
